apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: helloworld
  name: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - image: mayerparra/hello-world
        name: helloworld
        ports:
        - name: helloworld
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: helloworld
  name: helloworld
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 8090
      targetPort: 8080
  selector:
    name: helloworld
---

